image: docker:20  
services:
  - docker:dind  

variables:
  IMAGE_NAME: nikita1409/book-lib-management
  CONTAINER_NAME: book-lib-app
  PORT: 3000

stages:
  - build
  - deploy

before_script:
  - docker info  

build:
  stage: build
  script:
    - docker pull $IMAGE_NAME:latest || true  # Pull if exists
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME  

deploy:
  stage: deploy
  script:
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - docker run -d --name $CONTAINER_NAME -p $PORT:$PORT $IMAGE_NAME:latest
