image: docker:20

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: nikita1409/book-lib-management
  CONTAINER_NAME: book-lib-app
  PORT: 3000

before_script:
  - docker info

build:
  stage: build
  script:
    - echo "Pulling latest image from DockerHub..."
    - docker pull $IMAGE_NAME:latest

deploy:
  stage: deploy
  script:
    - echo "Stopping old container (if running)..."
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - echo "Starting new container..."
    - docker run -d --name $CONTAINER_NAME -p 3000:3000 $IMAGE_NAME:latest
