stages:
  - build
  - test
  - deploy

# Cache Docker layers to speed up builds
docker-build:
  stage: build
  script:
    - docker pull nikita1409/book-lib-management:latest  # Pull the image from Docker Hub
    - docker build -t nikita1409/book-lib-management .  # Build the image locally if needed
    - docker tag nikita1409/book-lib-management nikita1409/book-lib-management:latest  # Tag the image
  only:
    - master

# Run unit tests (assuming you have tests set up)
test:
  stage: test
  image: nikita1409/book-lib-management  # Use the Docker image to run tests
  script:
    - npm install  # Install dependencies if needed
    - npm test  # Run tests
  only:
    - master

# Deploy to the server (adjust to your deployment method)
deploy:
  stage: deploy
  script:
    - echo "Deploying the app to production..."
    - docker run -d -p 8080:8080 nikita1409/book-lib-management  # Example deployment command
  only:
    - master
