stages:
  - deploy

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Pulling the Docker image from Docker Hub..."
    - docker pull nikita1409/book-lib-management:latest
    - echo "Running the container..."
    - docker run -d -p 3000:3000 nikita1409/book-lib-management:latest
  only:
    - main  # Runs only on the main branch
