stages:
  - build
  - deploy

# Build Docker image
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind  # Docker in Docker service for building Docker images
  before_script:
    - docker info  # Check if Docker is running
  script:
    - docker build -t nikita1409/book-lib-management:$CI_COMMIT_SHA .  # Build the Docker image with commit SHA as tag
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  # Login to Docker Hub
    - docker push nikita1409/book-lib-management:$CI_COMMIT_SHA  # Push image to Docker Hub
  only:
    - main  # Only trigger this job for the main branch

# Deploy stage (optional, can be customized)
deploy:
  stage: deploy
  script:
    - echo "Deploying your app..."  # Replace this with actual deploy steps if required
  only:
    - main  # Deploy on the main branch
