stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - export PATH=$PATH:/usr/bin:/usr/local/bin
  script:
    - echo "Pulling Docker image..."
    - docker pull nikita1409/book-lib-management:latest
    - echo "Running Docker container..."
    - docker run -d -p 3000:3000 -p 3001:3001 nikita1409/book-lib-management:latest
  only:
    - main
