stages:
  - build
  - deploy

# Build Stage
build:
  stage: build
  image: docker:latest
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker info
  script:
    - docker build -t $DOCKER_USERNAME/book-lib-management .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push $DOCKER_USERNAME/book-lib-management

# Deploy Stage (optional, customize as needed)
deploy:
  stage: deploy
  script:
    - echo "Deployment step goes here (e.g., AWS, Kubernetes, etc.)"
