stages:
  - build
  - deploy

# Build stage (only if you want to rebuild the Docker image)
# Since you already pushed your image to Docker Hub, this stage is optional if the image doesn't need rebuilding.
build:
  stage: build
  script:
    - echo "Pulling Docker image from Docker Hub..."
    - docker pull nikita1409/book-lib-management:latest  # Pull your Docker image from Docker Hub
  only:
    - master  # Run this job only on the master branch

# Deploy stage
deploy:
  stage: deploy
  script:
    - echo "Running Docker container..."
    # Run the Docker container, exposing the app port 3000 and database port 3001
    - docker run -d -p 3000:3000 -p 3001:3001 nikita1409/book-lib-management:latest  # Run the Docker container with your image
  only:
    - master  # Run this job only on the master branch
