image: docker:20  # Use Docker image

services:
  - docker:dind  # Enable Docker-in-Docker

variables:
  DOCKER_HOST: tcp://docker:2375  # Connect to the Docker daemon
  DOCKER_TLS_CERTDIR: ""          # Disable TLS (needed for DinD)
  IMAGE_NAME: nikita1409/book-lib-management
  CONTAINER_NAME: book-lib-app
  PORT: 3000

stages:
  - build
  - deploy

before_script:
  - docker info  # Check Docker connectivity

build:
  stage: build
  script:
    - echo "Pulling latest image from DockerHub..."
    - docker pull $IMAGE_NAME:latest

deploy:
  stage: deploy
  script:
    - echo "Stopping old container (if running)..."
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - echo "Starting new container..."
    - docker run -d --name $CONTAINER_NAME -p $PORT:$PORT $IMAGE_NAME:latest
