stages:
  - deploy

deploy:
  stage: deploy
  image: nikita1409/book-lib-management:latest  # Use your Docker image here
  script:
    - echo "Deploying the Dockerized application using image nikita1409/book-lib-management"
    - docker run -d -p 3000:3000 nikita1409/book-lib-management:latest  # Run the image, mapping ports
