build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Verifying Docker installation..."
    - docker --version
    - echo "Building the Docker image..."
    - docker build -t nikita1409/book-lib-management:latest .
    - echo "Logging into Docker Hub..."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "Pushing the Docker image to Docker Hub..."
    - docker push nikita1409/book-lib-management:latest
  only:
    - main
