stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: nikita1409/book-lib-management:latest
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: $CI_REGISTRY_USER
  DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push $DOCKER_IMAGE
  only:
    - main

test:
  stage: test
  script:
    - echo "Running tests"
    - npm install
    - npm run test
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
    - docker pull $DOCKER_IMAGE
    - docker run -d -p 3000:3000 $DOCKER_IMAGE
  only:
    - main
