stages:
  - build

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Pulling pre-built Docker image..."
    - docker pull nikita-purohit1409/book-management:latest
    - echo "Image pulled successfully"
