version: '3'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: clue/json-server
    volumes:
      - ./db.json:/data/db.json
    ports:
      - "3001:3001"
